### ISSUE TITLE
Seperate internal and external URLs for radarr/sonarr

### ISSUE THREAD

**Issue by ayykamp** [aleksilassila/reiverr#147]
Currently the frontend connects directly to sonarr, which means docker network URLs like http://sonarr:8989 don't work. Ideally the backend should connect to sonarr and there should be an option to set an external URL (e.g. sonarr.example.com) which links from reiverr could use. This is what overseerr does as far as I understand.

**Comment by aleksilassila** [comment]
Right now the backend doesn't connect to the services at all, so there wouldn't be anything that the internal urls could be used for, as all requests originate from the browser. That's why you'll need to use an external url with reiverr. However, I plan on on proxying all requests through the backend at some point (configurable) (#52), which would eliminate the need for external urls. Would this solve the issue?

**Comment by ayykamp** [comment]
Ah sorry I didn't see that issue. 
That would solve it except if you ever want to have links from reiverr to sonarr (overseerr has this, a "Open in Sonarr" button).
