### ISSUE TITLE
No metadata for "User" was found.

### ISSUE THREAD

**Issue by Phelra** [aleksilassila/reiverr#154]
Since there have been some changes with the latest commits, when I launch the development mode I get a citematic error.

I follow this procedure:
Clone the repository
Check out the dev branch
Install dependencies
npm install
npm install --prefix backend
To start the frontend: npx vite --host
To start the backend: npm run --prefix backend start:dev

<img width="678" alt="image" src="https://github.com/user-attachments/assets/68815eba-83b8-4bc4-aca1-a5886f7b6659">

<img width="566" alt="image" src="https://github.com/user-attachments/assets/52700f28-6e76-4847-a821-9684c3a05ce4">

Maybe I've forgotten something but it worked in previous versions?

Thanks in advance :)

**Comment by aleksilassila** [comment]
Uhh if you have been testing the commits between releases, there has been some changes to the database and you might need to nuke it. Before that though you should try running the migrations to see if that makes a difference (i think the command is in backend/package.json). If this happened even if you have only used the official releases, let me know because then it's probably a bug. 

Also there's a chance it has something to do with [this](https://www.themoviedb.org/talk/66a38c36e0203a642b164683?page=1#66abb3a121368f47815c8b3a), it broke the tmdb integration temporarily.

**Comment by Phelra** [comment]
Great, thanks for your reply! The migration command: 
npm run typeorm:run-migrations && node dist/src/main 
Now it worked fine!
