### ISSUE TITLE
Jellyfin "Could not connect"

### ISSUE THREAD

**Issue by Joly0** [aleksilassila/reiverr#158]
Not sure what is wrong and what logs you might need, but when i enter the jellyfin base url and the api key i get the error "Could not connect"

**Comment by Phelra** [comment]
Hello ! Did you check the end of your url, you should not put “/” for example use “http://192.168.60.210:8096” and not “http://192.168.60.210:8096/” 😁 Otherwise, you need to inspect the elements in your browser if an error occurs.

<img width="637" alt="image" src="https://github.com/user-attachments/assets/aaa80bc6-576d-4252-86b1-4ca3df5704db">

**Comment by Joly0** [comment]
Ok, it works now. I used the dns name of my jellyfin instance, aswell as tried ip:port, but i used https instead of http, maybe that was the issue. It works with http
