### ISSUE TITLE
Implement settings page

### ISSUE THREAD

**Issue by aleksilassila** [aleksilassila/reiverr#5]

**Comment by mikeyounge** [comment]
Not sure if this is the place to leave this, but it looks like the src/lib/stores/settings.store.ts file has a place to adjust the quality and root path for Sonarr and Radarr. I'm hoping this is the unreleased settings page because I don't have these directories as you do and Sonarr hardcodes its placement of these into those default root folders. You have to manually relocate them after they have been added at this time. Following this project eagerly and hoping for Plex integration. I installed Jellyfin today just so I could play with this. Like it a lot so far. Wish I knew how to code so I could help.

**Comment by aleksilassila** [comment]
> Not sure if this is the place to leave this, but it looks like the src/lib/stores/settings.store.ts file has a place to adjust the quality and root path for Sonarr and Radarr. I'm hoping this is the unreleased settings page because I don't have these directories as you do and Sonarr hardcodes its placement of these into those default root folders. You have to manually relocate them after they have been added at this time. Following this project eagerly and hoping for Plex integration. I installed Jellyfin today just so I could play with this. Like it a lot so far. Wish I knew how to code so I could help.

All the values in settings.store.ts will be configurable via the /settings page whenever I get the chance to implement it, so stuff like quality profile and path being hard coded in will change. Also, plex integration is a planned feature but doesn't have the highest priority now 👍
