### ISSUE TITLE
Cors issue with Nginx Proxy Manager

### ISSUE THREAD

**Issue by GaetanPTX** [aleksilassila/reiverr#70]
Hello, I configured Nginx Proxy Manager without SSL to have a public address and share it with my family outside my home.

The problem is that I have a cors error when loading my pages, how can I fix this problem?

thanks

![image](https://github.com/aleksilassila/reiverr/assets/51859391/26669db8-7e25-4640-92f6-d413efdec5c3)

**Comment by aleksilassila** [comment]
In the screenshot are you accessing reiverr from outside your home network? If yes, you'd have to make sure the base urls in your reiverr configuration are accessible from outside your network, too, because your browser is making those requests for now, not the server in your home network.

This will change in the future, but for now I wouldn't expose Reiverr outside your home network, because all the api keys are sent to the browser and there's no authentication, meaning anyone who visits the page can see the api keys.

**Comment by GaetanPTX** [comment]
Ok thanks bro
